<?php
namespace utils;

/**
* Lang class
* 
* This class provides methods for getting and setting strings in different languages.
*/
class Lang
{
    /**
    * An associative array of strings in different languages
    * 
    * @var array
    */
    private static $strings = [
        'hun' => [
            'allFieldsRequired' => 'Minden mező kitöltése kötelező.',
            'automatonsButton' => 'Determinisztikus véges automaták',
            'automatonsTitle' => 'Determinisztikus véges automaták',
            'back' => 'Vissza',
            'backToTheMainPage' => 'Vissza a főoldalra',
            'baseSetNotDefinedError' => 'Az alaphalmaz (H) nem definiált. Definiáld az alaphalmazt és értékeltesd ki újra a kifejezést.',
            'cardinality' => 'Számosság',
            'clientTitle' => 'Főoldal',
            'complement' => 'Komplementer',
            'deleteAutomatonSuccessfullyCrud' => 'Az automatát ábrázoló kép sikeresen törölve.',
            'deleteFileSuccessfullyCrud' => 'A fájl sikeresen törölve.',
            'developerErrorMessages' => 'Fejlesztői hibaüzenetek.',
            'dfa'=>'DVA',
            'dfaOff' => 'DVA:ki',
            'dfaOn' => 'DVA:be',
            'dividedByZeroInBoundaryFunctionError'=>'Hiba! Nullával osztás nem megengedett.',
            'dividedByZeroInUserDefindedFunctionError'=>'Hiba! Nullával osztás nem megengedett.',
            'divides' => 'Osztja',
            'doesNotDivide' => 'Nem osztja',
            'download' => 'Letöltés',
            'elementOf' => 'Eleme',
            'emptyFileErrorLoad' => 'A fájl üres.',
            'emptyFileErrorSave' => 'A fájl üres.',
            'eng' => 'Angol',
            'equal' => 'Egyenlő',
            'errorMessages'=>'Hibaüzenetek',
            'errors' => 'Hibák',
            'expressionCopyError'=>'Hiba a kifejezések másolása közben.',
            'false' => 'hamis',
            'fileCopyError'=>'Hiba a fájl másolása közben.',
            'fileCopySuccess'=>'A fájl sikeresen lemásolva.',
            'fileTypeErrorLoad' => 'A fájl nem megfelelő típusú.',
            'filesButton' => 'Fájlok',
            'filesTitle' => 'Fájlok',
            'generalCrudError' => 'Hiba a művelet közben.',
            'generalFileErrorLoad' => 'Nem várt hiba történt a feltöltés közben.',
            'helpButton' => 'Használati útmutató',
            'helpTitle' => 'Használati útmutató',
            'hun' => 'Magyar',
            'identifierExpectedUser'=>'Azonosító, az azonosító csak alulvonást, angol kis- és nagybetűket, valamint számokat tartalmazhat, de nem kezdődhet számmal.',
            'incorrectFileErrorLoad' => 'A fájl hibás.',
            'intersection' => 'Metszet',
            'invalidArgumentsError'=>'Érvénytelen argumentumok ennél a függvénynél: ',
            'languageSelector'=>'Nyelvválasztó: ',
            'lexerErrorColumn' => 'Pozíció: ',
            'lexerErrorColumnUser' => ' Az utolsó helyes szimbólum pozíciója: ',
            'lexerErrorStart' => 'Az utolsó jó token: ',
            'lexerErrorStartUser' => 'Az utolsó helyes szimbólum: ',
            'load' => 'Munkalap betöltése',
            'logicalAnd' => 'Logikai és',
            'logicalOr' => 'Logikai vagy',
            'login' => 'Bejelentkezés',
            'loginError' => 'A felhasználónév vagy a jelszó hibás.',
            'logoutButton' => 'Kijelentkezés',
            'mathematicalMode' => 'Matematikai mód',
            'missingFileErrorLoad' => 'A fájl nem található.',
            'missingFileErrorSave' => 'A fájl nem található.',
            'missingFileIdErrorSave' => 'A fájlazonosító hiányzik.',
            'missingFileIdErrorLoad' => 'A fájlazonosító hiányzik.',
            'missingResourceEnd' => 'erőforrás nem található',
            'missingResourceStart' => 'A(z)',
            'misspelledIdentifier'=>'A képletben legalább az egyik azonosító hibásan van írva.',
            'mode'=>'Mód',
            'modifyFileRecordSuccessfullyCrud'=>'Fájl sikeresen módosítva.',
            'myFiles'=>'Fájljaim',
            'new' => 'Új',
            'noDiagrams'=>'Nincsenek diagramok.',
            'noFiles'=>'Nincsenek fájlok.',
            'notElementOf' => 'Nem eleme',
            'null' => 'null',
            'numberExpectedUser'=>'Egész szám',          
            'parserErrorAfterPositionUser' => '. karaktertől. Az utolsó helyes szimbólum: ',
            'parserErrorBeforePositionUser' => ' tudod folytatni a ',
            'parserErrorExpectedTokens' => 'az elvárt token a következők valamelyike: ',
            'parserErrorFunction' => '. a következő függvényben: ',
            'parserErrorPosition' => 'a következő pozícióban: ',
            'parserErrorStart' => 'Nem elvárt token',
            'parserErrorStartUser' => 'Szintaktikai hiba! Az alábbi szimbólumok valamelyikével ',
            'password' => 'Jelszó: ',
            'passwordAgain' => 'Jelszó újra: ',
            'passwordsNotTheSame' => 'A két jelszó nem egyezik.',
            'print' => 'Nyomtatás',
            'profileButton' => 'Profilom',
            'profileTitle' => 'Profilom',
            'programButton' => 'Program',
            'programTitle' => 'Program',
            'questionnaireDescription' => 'Gönczi Gábor vagyok a Széchenyi István Egyetem végzős hallgatója.<br/>Az alábbi kérdőívben az általam készített programhoz kapcsolódó kérdések találhatók.<br/>A kérdőív teljesen anonim.<br/>Köszönöm ha a  kitöltésével segíti a diplomamunkám elkészítését.',
            'questionnaireTitle' => 'Halmazok témakörének tanulását/tanítását segítő program',
            'questionnaireAverageDailyUsageInMinute' => 'Átlagosan mennyi ideig használta a programot naponta (percben mérve)?',
            'questionnaireButton' => 'Kérdőív',
            'questionnaireExtendProgram' => 'Ha van olyan része a programnak, amin változtatna vagy olyan funkció, amivel kibővítené a programot, akkor kérem írja le ezt néhány mondatban.',
            'questionnaireGender' => 'Neme?',
            'questionnaireGenderFemale' => 'Nő',
            'questionnaireGenderMale' => 'Férfi',
            'questionnaireMathKnowledgeAfterProgramUsage' => 'Ön szerint javult a matematika tudása a program használatával?',
            'questionnaireMathKnowledgeByMark' => 'Érdemjegyei alapján milyen az Ön matematikatudása?',
            'questionnaireNo' => 'Nem',
            'questionnaireProgramConductiveness' => 'Ön szerint mennyire hasznos a program?',
            'questionnaireProgramConductivenessHigh' => 'Nagyon hasznos',
            'questionnaireProgramConductivenessLow' => 'Egyáltalán nem hasznos',
            'questionnaireProgramUsageTimOfTheDay' => 'Mikor használta a programot általában?',
            'questionnaireProgramUsageTimOfTheDayAfternoon' => 'Délután',
            'questionnaireProgramUsageTimOfTheDayBeforenoon' => 'Délelőtt',
            'questionnaireProgramUsageTimOfTheDayMorning' => 'Reggel',
            'questionnaireProgramUsageTimOfTheDayWeekdays' => 'Hétköznap',
            'questionnaireProgramUsageTimOfTheDayWeekends' => 'Hétvégén',
            'questionnaireRecommendationToTry' => 'Ajánlaná ismerősének?',
            'questionnaireRecommendationToTryDesc' => 'Kérem fejtse ki az előző kérdésre adott válaszát.',
            'questionnairePageTitle' => 'Kérdőív',
            'questionnaireUnknownError' => 'Ismeretlen hiba történt a kérdőív beküldése közben!',
            'questionnaireUserSatisfaction' => 'Mennyire elégedett a program következő jellemzőivel?',
            'questionnaireUserSatisfactionCurriculumsize' => 'A gyakorolható tananyagrész nagyságával',
            'questionnaireUserSatisfactionDesign' => 'Dizájn',
            'questionnaireUserSatisfactionErrormessages' => 'A hibaüzenetek egyértelműségével',
            'questionnaireUserSatisfactionExample' => 'A halmazok témakörét feldolgozó mintafájllal',
            'questionnaireUserSatisfactionTutorial' => 'A használatot bemutató videóval',
            'questionnaireYes' => 'Igen',
            'questionnairemessageError' => 'Hiba történt a kérdőív mentése közben.',
            'questionnairemessageSuccess' => 'Köszönöm, hogy a kérdőív kitöltésével támogattad a diplomamunkám elkészítését.',
            'realSubsetOf' => 'Valódi részhalmaz',
            'register' => 'Regisztráció',
            'saveProfileSettings' => 'Beállítások mentése',
            'setminus' => 'Különbség',
            'settingsSaved'=>'Beállítások elmentve.',
            'sharedFiles'=>'Megosztott fájlok',
            'subsetOf' => 'Részhalmaz',
            'textMode' => 'Szöveges mód',
            'toBeEqual' => 'Legyen egyenlő',
            'true' => 'igaz',
            'undefinedVariableErrorStart'=>'A(z) ',
            'undefinedVariableErrorEnd'=>' nevű változó nem definiált.',
            'undefinedVariablesError'=>'A következő változók nincsenek definiálva: ',
            'union' => 'Únió',
            'unknownRegisterError' => 'Sikertelen regisztráció ismeretlen okból.',
            'userErrorMessages' => 'Felhasználóbarát hibaüzenetek',
            'username' => 'Felhasználónév',
            'usernameIsAlreadyExist' => 'A felhasználónév foglalt.',
            'variableCopyError'=>'Hiba a változók másolása közben.',
            'variables' => 'Változók',
        ],
        'eng' => [
            'allFieldsRequired' => 'All fields required.',
            'automatonsButton' => 'Deterministic finite automata',
            'automatonsTitle' => 'Deterministic finite automata',
            'back' => 'Back',
            'backToTheMainPage' => 'Back to main page',
            'baseSetNotDefinedError' => 'The base set (H) is not defined. Define the base set and re-evaluate the expression.',
            'cardinality' => 'Cardinality',
            'clientTitle' => 'Home',
            'complement' => 'Complementer',
            'deleteAutomatonSuccessfullyCrud' => 'Image of automaton successfully deleted.',
            'deleteFileSuccessfullyCrud' => 'File successfully deleted.',
            'developerErrorMessages' => 'Developer error messages',
            'dfa'=>'DFA',
            'dfaOff' => 'DVA:off',
            'dfaOn' => 'DVA:on',
            'dividedByZeroInBoundaryFunctionError'=>'Error! Division by zero is not allowed.',
            'dividedByZeroInUserDefindedFunctionError'=>'Error! Division by zero is not allowed.',
            'divides' => 'Divides',
            'doesNotDivide' => 'Does not divide',
            'download' => 'Download',
            'elementOf' => 'Element of',
            'emptyFileErrorLoad' => 'File is empty.',
            'emptyFileErrorSave' => 'File is empty.',
            'eng' => 'English',
            'equal' => 'Equal',
            'errorMessages'=>'Error messages',
            'errors' => 'Errors',
            'expressionCopyError'=>'Error during expressions copying.',
            'false' => 'false',
            'fileCopyError'=>'Error during file copying.',
            'fileCopySuccess'=>'File successfully copied.',
            'fileNotCopyableError'=>'File is not copyable.',
            'fileTypeErrorLoad' => 'File is not of the correct type.',
            'filesButton' => 'Files',
            'filesTitle' => 'Files',
            'generalCrudError' => 'Error during operation.',
            'generalFileErrorLoad' => 'An unexpected error occurred during loading.',
            'helpButton' => 'User Guide',
            'helpTitle' => 'User Guide',
            'hun' => 'Hungarian',
            'identifierExpectedUser'=>'Identifier, the identifier can only contain underscores, upper and lower case letters and numbers, but cannot start with a number.',
            'incorrectFileErrorLoad' => 'The file is incorrect.',
            'intersection' => 'Intersection',
            'invalidArgumentsError'=>'Invalid arguments for this function: ',
            'languageSelector'=>'Language selector: ',
            'lexerErrorColumn' => ' Position:',
            'lexerErrorColumnUser' => ' Position of last correct character: ',
            'lexerErrorStart' => 'Last good token is: ',
            'lexerErrorStartUser' => 'The last correct symbol is: ',
            'load' => 'Load worksheet',
            'logicalAnd' => 'Logical and',
            'logicalOr' => 'Logical or',
            'login' => 'Login',
            'loginError' => 'Username or password is incorrect.',
            'logoutButton' => 'Logout',
            'mathematicalMode' => 'Mathematical mode',
            'missingFileErrorLoad' => 'File not found.',
            'missingFileErrorSave' => 'File not found.',
            'missingFileIdErrorSave' => 'File ID is missing.',
            'missingFileIdErrorLoad' => 'File ID is missing.',
            'missingResourceEnd' => 'resource not found.',
            'missingResourceStart' => 'The',
            'misspelledIdentifier'=>'At least one of the identifiers is misspelled in the formula.',
            'mode'=>'Mode',
            'modifyFileRecordSuccessfullyCrud'=>'File modified successfully.',
            'myFiles'=>'My Files',
            'new' => 'New',
            'noDiagrams'=>'There are no diagrams.',
            'noFiles'=>'There are no files.',
            'notElementOf' => 'Not element of',
            'null' => 'null',
            'numberExpectedUser'=>'Whole number',
            'parserErrorAfterPositionUser' => '. character. The last correct symbol is:  ',
            'parserErrorBeforePositionUser' => ' you can continue from the ',
            'parserErrorExpectedTokens' => 'the expected token is one of the following: ',
            'parserErrorFunction' => ' . in the following function: ',
            'parserErrorPosition' => 'in the next position ',
            'parserErrorStart' => 'Not expected token',
            'parserErrorStartUser' => 'Syntactic error! With one of the following symbols ',
            'password' => 'Password',
            'passwordAgain' => 'Password again',
            'passwordsNotTheSame' => 'The two passwords do not match.',
            'print' => 'Print',
            'profileButton' => 'My profile',
            'profileTitle' => 'My profile',
            'programButton' => 'Program',
            'programTitle' => 'Program',
            'questionnaireDescription' => 'I am Gábor Gönczi, a graduate student at Széchenyi István University.<br />The following questionnaire contains questions related to the programme I have created.<br />The questionnaire is completely anonymous.<br />Thank you if you fill it in to help me with my thesis.',
            'questionnaireTitle' => 'Program to help learning/teaching about sets',
            'questionnaireAverageDailyUsageInMinute' => 'On average, how much time did you use the program per day (measured in minutes)?',
            'questionnaireButton' => 'Questionnaire',
            'questionnaireExtendProgram' => 'If there is a part of the program you would like to change or a feature you would like to extend, please describe it in a few sentences',
            'questionnaireGender' => 'Gender?',
            'questionnaireGenderFemale' => 'Female',
            'questionnaireGenderMale' => 'Male',
            'questionnaireMathKnowledgeAfterProgramUsage' => 'Do you think your math knowledge improved after using the program?',
            'questionnaireMathKnowledgeByMark' => 'Based on your marks, how is your math knowledge?',
            'questionnaireNo' => 'No',
            'questionnaireProgramConductiveness' => 'How useful do you think the program is?',
            'questionnaireProgramConductivenessHigh' => 'Very useful',
            'questionnaireProgramConductivenessLow' => 'Not at all useful',
            'questionnaireProgramUsageTimOfTheDay' => 'When did you usually use the program?',
            'questionnaireProgramUsageTimOfTheDayAfternoon' => 'Afternoon',
            'questionnaireProgramUsageTimOfTheDayBeforenoon' => 'Morning',
            'questionnaireProgramUsageTimOfTheDayWeekdays' => 'Weekday',
            'questionnaireProgramUsageTimOfTheDayWeekends' => 'Weekends',
            'questionnaireRecommendationToTry' => 'Would you recommend to a friend?',
            'questionnaireRecommendationToTryDesc' => 'Please explain your answer to the previous question',
            'questionnairePageTitle' => 'Questionnaire',
            'questionnaireUnknownError' => 'An unknown error occurred while submitting the questionnaire!',
            'questionnaireUserSatisfaction' => 'How satisfied are you with the following program features?',
            'questionnaireUserSatisfactionCurriculumsize' => 'The size of the curriculum part you can practice',
            'questionnaireUserSatisfactionDesign' => 'Design',
            'questionnaireUserSatisfactionErrormessages' => 'Clarity of error messages',
            'questionnaireUserSatisfactionExample' => 'Sample file on the topic of sets',
            'questionnaireUserSatisfactionTutorial' => 'With a video tutorial on usage',
            'questionnaireYes' => 'Yes',
            'questionnairemessageError' => 'An error occurred while saving the questionnaire.',
            'questionnairemessageSuccess' => 'Thank you for supporting my thesis by completing the questionnaire.',
            'realSubsetOf' => 'Real subset of',
            'register' => 'Register',
            'saveProfileSettings' => 'Save Settings',
            'setminus' => 'Difference',
            'settingsSaved'=>'Settings saved.',
            'sharedFiles'=>'Shared files',
            'subsetOf' => 'Subset of',
            'textMode' => 'Text mode',
            'toBeEqual' => 'Be equal',
            'true' => 'true',
            'undefinedVariableErrorStart'=>'Variable called ',
            'undefinedVariableErrorEnd'=>' does not defined.',
            'undefinedVariablesError'=>'The following variables are not defined: ',
            'union' => 'Union',
            'unknownRegisterError' => 'Failed registration for unknown reason.',
            'userErrorMessages' => 'User-friendly error messages',
            'username' => 'Username',
            'usernameIsAlreadyExist' => 'Username is already registered.',
            'variableCopyError'=>'Error during variables copying.',
            'variables' => 'Variables',
        ]
    ];

    /**
    * Returns the string corresponding to the given key and language
    * 
    * @param string $string The key of the string
    * @param string $lang The language of the string (default: 'hun')
    * @return string The string value
    */
    public static function getString($string, $lang = 'hun')
    {
        return self::$strings[$lang][$string];
    }

    /**
    * Returns an array of available languages
    * 
    * @return array The array of language codes
    */
    public static function getLangs()
    {
        return ['eng', 'hun'];
    }
}
