<?php

use \PHPUnit\Framework\TestCase;
use \utils\Lang;

class LangTest extends TestCase
{

    public function testGetLangs()
    {

        $langs = Lang::getLangs();
        $this->assertIsArray($langs);
        $this->assertContains('eng', $langs);
        $this->assertContains('hun', $langs);
    }

    /**
     * @dataProvider getStringProvider
     */
    public function testGetString($lang, $stringName, $expected)
    {
        $this->assertEquals($expected, Lang::getString($stringName, $lang));
    }

    public static function getStringProvider()
    {

        return [
            ['hun', 'allFieldsRequired', 'Minden mező kitöltése kötelező.'],
            ['hun', 'automatonsButton', 'Determinisztikus véges automaták'],
            ['hun', 'automatonsTitle', 'Determinisztikus véges automaták'],
            ['hun', 'back', 'Vissza'],
            ['hun', 'backToTheMainPage', 'Vissza a főoldalra'],
            ['hun', 'baseSetNotDefinedError', 'Az alaphalmaz (H) nem definiált. Definiáld az alaphalmazt és értékeltesd ki újra a kifejezést.'],
            ['hun', 'cardinality', 'Számosság'],
            ['hun', 'clientTitle', 'Főoldal'],
            ['hun', 'complement', 'Komplementer'],
            ['hun', 'deleteAutomatonSuccessfullyCrud', 'Az automatát ábrázoló kép sikeresen törölve.'],
            ['hun', 'deleteFileSuccessfullyCrud', 'A fájl sikeresen törölve.'],
            ['hun', 'developerErrorMessages', 'Fejlesztői hibaüzenetek.'],
            ['hun', 'dfa', 'DVA'],
            ['hun', 'dfaOff', 'DVA:ki'],
            ['hun', 'dfaOn', 'DVA:be'],
            ['hun', 'dividedByZeroInBoundaryFunctionError', 'Hiba! Nullával osztás nem megengedett.'],
            ['hun', 'dividedByZeroInUserDefindedFunctionError', 'Hiba! Nullával osztás nem megengedett.'],
            ['hun', 'divides', 'Osztja'],
            ['hun', 'doesNotDivide', 'Nem osztja'],
            ['hun', 'download', 'Letöltés'],
            ['hun', 'elementOf', 'Eleme'],
            ['hun', 'emptyFileErrorLoad', 'A fájl üres.'],
            ['hun', 'emptyFileErrorSave', 'A fájl üres.'],
            ['hun', 'eng', 'Angol'],
            ['hun', 'equal', 'Egyenlő'],
            ['hun', 'errorMessages', 'Hibaüzenetek'],
            ['hun', 'errors', 'Hibák'],
            ['hun', 'expressionCopyError', 'Hiba a kifejezések másolása közben.'],
            ['hun', 'false', 'hamis'],
            ['hun', 'fileCopyError', 'Hiba a fájl másolása közben.'],
            ['hun', 'fileCopySuccess', 'A fájl sikeresen lemásolva.'],
            ['hun', 'fileTypeErrorLoad', 'A fájl nem megfelelő típusú.'],
            ['hun', 'filesButton', 'Fájlok'],
            ['hun', 'filesTitle', 'Fájlok'],
            ['hun', 'generalCrudError', 'Hiba a művelet közben.'],
            ['hun', 'generalFileErrorLoad', 'Nem várt hiba történt a feltöltés közben.'],
            ['hun', 'helpButton', 'Használati útmutató'],
            ['hun', 'helpTitle', 'Használati útmutató'],
            ['hun', 'hun', 'Magyar'],
            ['hun', 'identifierExpectedUser', 'Azonosító, az azonosító csak alulvonást, angol kis- és nagybetűket, valamint számokat tartalmazhat, de nem kezdődhet számmal.'],
            ['hun', 'incorrectFileErrorLoad', 'A fájl hibás.'],
            ['hun', 'intersection', 'Metszet'],
            ['hun', 'invalidArgumentsError', 'Érvénytelen argumentumok ennél a függvénynél: '],
            ['hun', 'languageSelector', 'Nyelvválasztó: '],
            ['hun', 'lexerErrorColumn', 'Pozíció: '],
            ['hun', 'lexerErrorColumnUser', ' Az utolsó helyes szimbólum pozíciója: '],
            ['hun', 'lexerErrorStart', 'Az utolsó jó token: '],
            ['hun', 'lexerErrorStartUser', 'Az utolsó helyes szimbólum: '],
            ['hun', 'load', 'Munkalap betöltése'],
            ['hun', 'logicalAnd', 'Logikai és'],
            ['hun', 'logicalOr', 'Logikai vagy'],
            ['hun', 'login', 'Bejelentkezés'],
            ['hun', 'loginError', 'A felhasználónév vagy a jelszó hibás.'],
            ['hun', 'logoutButton', 'Kijelentkezés'],
            ['hun', 'mathematicalMode', 'Matematikai mód'],
            ['hun', 'missingFileErrorLoad', 'A fájl nem található.'],
            ['hun', 'missingFileErrorSave', 'A fájl nem található.'],
            ['hun', 'missingFileIdErrorSave', 'A fájlazonosító hiányzik.'],
            ['hun', 'missingFileIdErrorLoad', 'A fájlazonosító hiányzik.'],
            ['hun', 'missingResourceEnd', 'erőforrás nem található'],
            ['hun', 'missingResourceStart', 'A(z)'],
            ['hun', 'misspelledIdentifier', 'A képletben legalább az egyik azonosító hibásan van írva.'],
            ['hun', 'mode', 'Mód'],
            ['hun', 'modifyFileRecordSuccessfullyCrud', 'Fájl sikeresen módosítva.'],
            ['hun', 'myFiles', 'Fájljaim'],
            ['hun', 'new', 'Új'],
            ['hun', 'noDiagrams', 'Nincsenek diagramok.'],
            ['hun', 'noFiles', 'Nincsenek fájlok.'],
            ['hun', 'notElementOf', 'Nem eleme'],
            ['hun', 'null', 'null'],
            ['hun', 'numberExpectedUser', 'Egész szám'],
            ['hun', 'parserErrorAfterPositionUser', '. karaktertől. Az utolsó helyes szimbólum: '],
            ['hun', 'parserErrorBeforePositionUser', ' tudod folytatni a '],
            ['hun', 'parserErrorExpectedTokens', 'az elvárt token a következők valamelyike: '],
            ['hun', 'parserErrorFunction', '. a következő függvényben: '],
            ['hun', 'parserErrorPosition', 'a következő pozícióban: '],
            ['hun', 'parserErrorStart', 'Nem elvárt token'],
            ['hun', 'parserErrorStartUser', 'Szintaktikai hiba! Az alábbi szimbólumok valamelyikével '],
            ['hun', 'password', 'Jelszó: '],
            ['hun', 'passwordAgain', 'Jelszó újra: '],
            ['hun', 'passwordsNotTheSame', 'A két jelszó nem egyezik.'],
            ['hun', 'print', 'Nyomtatás'],
            ['hun', 'profileButton', 'Profilom'],
            ['hun', 'profileTitle', 'Profilom'],
            ['hun', 'programButton', 'Program'],
            ['hun', 'programTitle', 'Program'],
            ['hun','questionnaireDescription', 'Gönczi Gábor vagyok a Széchenyi István Egyetem végzős hallgatója.<br/>Az alábbi kérdőívben az általam készített programhoz kapcsolódó kérdések találhatók.<br/>A kérdőív teljesen anonim.<br/>Köszönöm ha a  kitöltésével segíti a diplomamunkám elkészítését.'],
            ['hun', 'questionnaireTitle', 'Halmazok témakörének tanulását/tanítását segítő program'],
            ['hun', 'questionnaireAverageDailyUsageInMinute', 'Átlagosan mennyi ideig használta a programot naponta (percben mérve)?'],
            ['hun', 'questionnaireButton', 'Kérdőív'],
            ['hun', 'questionnaireExtendProgram', 'Ha van olyan része a programnak, amin változtatna vagy olyan funkció, amivel kibővítené a programot, akkor kérem írja le ezt néhány mondatban.'],
            ['hun', 'questionnaireGender', 'Neme?'],
            ['hun', 'questionnaireGenderFemale', 'Nő'],
            ['hun', 'questionnaireGenderMale', 'Férfi'],
            ['hun', 'questionnaireMathKnowledgeAfterProgramUsage', 'Ön szerint javult a matematika tudása a program használatával?'],
            ['hun', 'questionnaireMathKnowledgeByMark', 'Érdemjegyei alapján milyen az Ön matematikatudása?'],
            ['hun', 'questionnaireNo', 'Nem'],
            ['hun', 'questionnaireProgramConductiveness', 'Ön szerint mennyire hasznos a program?'],
            ['hun', 'questionnaireProgramConductivenessHigh', 'Nagyon hasznos'],
            ['hun', 'questionnaireProgramConductivenessLow', 'Egyáltalán nem hasznos'],
            ['hun', 'questionnaireProgramUsageTimOfTheDay', 'Mikor használta a programot általában?'],
            ['hun', 'questionnaireProgramUsageTimOfTheDayAfternoon', 'Délután'],
            ['hun', 'questionnaireProgramUsageTimOfTheDayBeforenoon', 'Délelőtt'],
            ['hun', 'questionnaireProgramUsageTimOfTheDayMorning', 'Reggel'],
            ['hun', 'questionnaireProgramUsageTimOfTheDayWeekdays', 'Hétköznap'],
            ['hun', 'questionnaireProgramUsageTimOfTheDayWeekends', 'Hétvégén'],
            ['hun', 'questionnaireRecommendationToTry', 'Ajánlaná ismerősének?'],
            ['hun', 'questionnaireRecommendationToTryDesc', 'Kérem fejtse ki az előző kérdésre adott válaszát.'],
            ['hun', 'questionnairePageTitle', 'Kérdőív'],
            ['hun', 'questionnaireUnknownError', 'Ismeretlen hiba történt a kérdőív beküldése közben!'],
            ['hun', 'questionnaireUserSatisfaction', 'Mennyire elégedett a program következő jellemzőivel?'],
            ['hun', 'questionnaireUserSatisfactionCurriculumsize', 'A gyakorolható tananyagrész nagyságával'],
            ['hun', 'questionnaireUserSatisfactionDesign', 'Dizájn'],
            ['hun', 'questionnaireUserSatisfactionErrormessages', 'A hibaüzenetek egyértelműségével'],
            ['hun', 'questionnaireUserSatisfactionExample', 'A halmazok témakörét feldolgozó mintafájllal'],
            ['hun', 'questionnaireUserSatisfactionTutorial', 'A használatot bemutató videóval'],
            ['hun', 'questionnaireYes', 'Igen'],
            ['hun', 'questionnairemessageError', 'Hiba történt a kérdőív mentése közben.'],
            ['hun', 'questionnairemessageSuccess', 'Köszönöm, hogy a kérdőív kitöltésével támogattad a diplomamunkám elkészítését.'],
            ['hun', 'realSubsetOf', 'Valódi részhalmaz'],
            ['hun', 'register', 'Regisztráció'],
            ['hun', 'saveProfileSettings', 'Beállítások mentése'],
            ['hun', 'setminus', 'Különbség'],
            ['hun', 'settingsSaved', 'Beállítások elmentve.'],
            ['hun', 'sharedFiles', 'Megosztott fájlok'],
            ['hun', 'subsetOf', 'Részhalmaz'],
            ['hun', 'textMode', 'Szöveges mód'],
            ['hun', 'toBeEqual', 'Legyen egyenlő'],
            ['hun', 'true', 'igaz'],
            ['hun', 'undefinedVariableErrorStart', 'A(z) '],
            ['hun', 'undefinedVariableErrorEnd', ' nevű változó nem definiált.'],
            ['hun', 'undefinedVariablesError', 'A következő változók nincsenek definiálva: '],
            ['hun', 'union', 'Únió'],
            ['hun', 'unknownRegisterError', 'Sikertelen regisztráció ismeretlen okból.'],
            ['hun', 'userErrorMessages', 'Felhasználóbarát hibaüzenetek'],
            ['hun', 'username', 'Felhasználónév'],
            ['hun', 'usernameIsAlreadyExist', 'A felhasználónév foglalt.'],
            ['hun', 'variableCopyError', 'Hiba a változók másolása közben.'],
            ['hun', 'variables', 'Változók'],
            ['hun', 'wrongTypeForOperation','A művelet két operandusa nem megfelelő típusú.'],
            ['eng', 'allFieldsRequired', 'All fields required.'],
            ['eng', 'automatonsButton', 'Deterministic finite automata'],
            ['eng', 'automatonsTitle', 'Deterministic finite automata'],
            ['eng', 'back', 'Back'],
            ['eng', 'backToTheMainPage', 'Back to main page'],
            ['eng', 'baseSetNotDefinedError', 'The base set (H) is not defined. Define the base set and re-evaluate the expression.'],
            ['eng', 'cardinality', 'Cardinality'],
            ['eng', 'clientTitle', 'Home'],
            ['eng', 'complement', 'Complementer'],
            ['eng', 'deleteAutomatonSuccessfullyCrud', 'Image of automaton successfully deleted.'],
            ['eng', 'deleteFileSuccessfullyCrud', 'File successfully deleted.'],
            ['eng', 'developerErrorMessages', 'Developer error messages'],
            ['eng', 'dfa', 'DFA'],
            ['eng', 'dfaOff', 'DVA:off'],
            ['eng', 'dfaOn', 'DVA:on'],
            ['eng', 'dividedByZeroInBoundaryFunctionError', 'Error! Division by zero is not allowed.'],
            ['eng', 'dividedByZeroInUserDefindedFunctionError', 'Error! Division by zero is not allowed.'],
            ['eng', 'divides', 'Divides'],
            ['eng', 'doesNotDivide', 'Does not divide'],
            ['eng', 'download', 'Download'],
            ['eng', 'elementOf', 'Element of'],
            ['eng', 'emptyFileErrorLoad', 'File is empty.'],
            ['eng', 'emptyFileErrorSave', 'File is empty.'],
            ['eng', 'eng', 'English'],
            ['eng', 'equal', 'Equal'],
            ['eng', 'errorMessages', 'Error messages'],
            ['eng', 'errors', 'Errors'],
            ['eng', 'expressionCopyError', 'Error during expressions copying.'],
            ['eng', 'false', 'false'],
            ['eng', 'fileCopyError', 'Error during file copying.'],
            ['eng', 'fileCopySuccess', 'File successfully copied.'],
            ['eng', 'fileNotCopyableError', 'File is not copyable.'],
            ['eng', 'fileTypeErrorLoad', 'File is not of the correct type.'],
            ['eng', 'filesButton', 'Files'],
            ['eng', 'filesTitle', 'Files'],
            ['eng', 'generalCrudError', 'Error during operation.'],
            ['eng', 'generalFileErrorLoad', 'An unexpected error occurred during loading.'],
            ['eng', 'helpButton', 'User Guide'],
            ['eng', 'helpTitle', 'User Guide'],
            ['eng', 'hun', 'Hungarian'],
            ['eng', 'identifierExpectedUser', 'Identifier, the identifier can only contain underscores, upper and lower case letters and numbers, but cannot start with a number.'],
            ['eng', 'incorrectFileErrorLoad', 'The file is incorrect.'],
            ['eng', 'intersection', 'Intersection'],
            ['eng', 'invalidArgumentsError', 'Invalid arguments for this function: '],
            ['eng', 'languageSelector', 'Language selector: '],
            ['eng', 'lexerErrorColumn', ' Position:'],
            ['eng', 'lexerErrorColumnUser', ' Position of last correct character: '],
            ['eng', 'lexerErrorStart', 'Last good token is: '],
            ['eng', 'lexerErrorStartUser', 'The last correct symbol is: '],
            ['eng', 'load', 'Load worksheet'],
            ['eng', 'logicalAnd', 'Logical and'],
            ['eng', 'logicalOr', 'Logical or'],
            ['eng', 'login', 'Login'],
            ['eng', 'loginError', 'Username or password is incorrect.'],
            ['eng', 'logoutButton', 'Logout'],
            ['eng', 'mathematicalMode', 'Mathematical mode'],
            ['eng', 'missingFileErrorLoad', 'File not found.'],
            ['eng', 'missingFileErrorSave', 'File not found.'],
            ['eng', 'missingFileIdErrorSave', 'File ID is missing.'],
            ['eng', 'missingFileIdErrorLoad', 'File ID is missing.'],
            ['eng', 'missingResourceEnd', 'resource not found.'],
            ['eng', 'missingResourceStart', 'The'],
            ['eng', 'misspelledIdentifier', 'At least one of the identifiers is misspelled in the formula.'],
            ['eng', 'mode', 'Mode'],
            ['eng', 'modifyFileRecordSuccessfullyCrud', 'File modified successfully.'],
            ['eng', 'myFiles', 'My Files'],
            ['eng', 'new', 'New'],
            ['eng', 'noDiagrams', 'There are no diagrams.'],
            ['eng', 'noFiles', 'There are no files.'],
            ['eng', 'notElementOf', 'Not element of'],
            ['eng', 'null', 'null'],
            ['eng', 'numberExpectedUser', 'Whole number'],
            ['eng', 'parserErrorAfterPositionUser', '. character. The last correct symbol is:  '],
            ['eng', 'parserErrorBeforePositionUser', ' you can continue from the '],
            ['eng', 'parserErrorExpectedTokens', 'the expected token is one of the following: '],
            ['eng', 'parserErrorFunction', ' . in the following function: '],
            ['eng', 'parserErrorPosition', 'in the next position '],
            ['eng', 'parserErrorStart', 'Not expected token'],
            ['eng', 'parserErrorStartUser', 'Syntactic error! With one of the following symbols '],
            ['eng', 'password', 'Password'],
            ['eng', 'passwordAgain', 'Password again'],
            ['eng', 'passwordsNotTheSame', 'The two passwords do not match.'],
            ['eng', 'print', 'Print'],
            ['eng', 'profileButton', 'My profile'],
            ['eng', 'profileTitle', 'My profile'],
            ['eng', 'programButton', 'Program'],
            ['eng', 'programTitle', 'Program'],
            ['eng','questionnaireDescription', 'I am Gábor Gönczi, a graduate student at Széchenyi István University.<br />The following questionnaire contains questions related to the programme I have created.<br />The questionnaire is completely anonymous.<br />Thank you if you fill it in to help me with my thesis.'],
            ['eng', 'questionnaireTitle', 'Program to help learning/teaching about sets'],
            ['eng', 'questionnaireAverageDailyUsageInMinute', 'On average, how much time did you use the program per day (measured in minutes)?'],
            ['eng', 'questionnaireButton', 'Questionnaire'],
            ['eng', 'questionnaireExtendProgram', 'If there is a part of the program you would like to change or a feature you would like to extend, please describe it in a few sentences'],
            ['eng', 'questionnaireGender', 'Gender?'],
            ['eng', 'questionnaireGenderFemale', 'Female'],
            ['eng', 'questionnaireGenderMale', 'Male'],
            ['eng', 'questionnaireMathKnowledgeAfterProgramUsage', 'Do you think your math knowledge improved after using the program?'],
            ['eng', 'questionnaireMathKnowledgeByMark', 'Based on your marks, how is your math knowledge?'],
            ['eng', 'questionnaireNo', 'No'],
            ['eng', 'questionnaireProgramConductiveness', 'How useful do you think the program is?'],
            ['eng', 'questionnaireProgramConductivenessHigh', 'Very useful'],
            ['eng', 'questionnaireProgramConductivenessLow', 'Not at all useful'],
            ['eng', 'questionnaireProgramUsageTimOfTheDay', 'When did you usually use the program?'],
            ['eng', 'questionnaireProgramUsageTimOfTheDayAfternoon', 'Afternoon'],
            ['eng', 'questionnaireProgramUsageTimOfTheDayBeforenoon', 'Morning'],
            ['eng', 'questionnaireProgramUsageTimOfTheDayWeekdays', 'Weekday'],
            ['eng', 'questionnaireProgramUsageTimOfTheDayWeekends', 'Weekends'],
            ['eng', 'questionnaireRecommendationToTry', 'Would you recommend to a friend?'],
            ['eng', 'questionnaireRecommendationToTryDesc', 'Please explain your answer to the previous question'],
            ['eng', 'questionnairePageTitle', 'Questionnaire'],
            ['eng', 'questionnaireUnknownError', 'An unknown error occurred while submitting the questionnaire!'],
            ['eng', 'questionnaireUserSatisfaction', 'How satisfied are you with the following program features?'],
            ['eng', 'questionnaireUserSatisfactionCurriculumsize', 'The size of the curriculum part you can practice'],
            ['eng', 'questionnaireUserSatisfactionDesign', 'Design'],
            ['eng', 'questionnaireUserSatisfactionErrormessages', 'Clarity of error messages'],
            ['eng', 'questionnaireUserSatisfactionExample', 'Sample file on the topic of sets'],
            ['eng', 'questionnaireUserSatisfactionTutorial', 'With a video tutorial on usage'],
            ['eng', 'questionnaireYes', 'Yes'],
            ['eng', 'questionnairemessageError', 'An error occurred while saving the questionnaire.'],
            ['eng', 'questionnairemessageSuccess', 'Thank you for supporting my thesis by completing the questionnaire.'],
            ['eng', 'realSubsetOf', 'Real subset of'],
            ['eng', 'register', 'Register'],
            ['eng', 'saveProfileSettings', 'Save Settings'],
            ['eng', 'setminus', 'Difference'],
            ['eng', 'settingsSaved', 'Settings saved.'],
            ['eng', 'sharedFiles', 'Shared files'],
            ['eng', 'subsetOf', 'Subset of'],
            ['eng', 'textMode', 'Text mode'],
            ['eng', 'toBeEqual', 'Be equal'],
            ['eng', 'true', 'true'],
            ['eng', 'undefinedVariableErrorStart', 'Variable called '],
            ['eng', 'undefinedVariableErrorEnd', ' does not defined.'],
            ['eng', 'undefinedVariablesError', 'The following variables are not defined: '],
            ['eng', 'union', 'Union'],
            ['eng', 'unknownRegisterError', 'Failed registration for unknown reason.'],
            ['eng', 'userErrorMessages', 'User-friendly error messages'],
            ['eng', 'username', 'Username'],
            ['eng', 'usernameIsAlreadyExist', 'Username is already registered.'],
            ['eng', 'variableCopyError', 'Error during variables copying.'],
            ['eng', 'variables', 'Variables'],
            ['eng', 'wrongTypeForOperation','Two operands of the operation are not of the correct type.'],

        ];

    }
}